---
# tasks file for mysql

---
# tasks file for mysql
- name: Install mysql
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'mysql-server', 'python3-pymysql' ]

# MySql Configuration

- name: Sets the password
  mysql_user:
    name: ansible
    password: "{{ root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Creates App Database
  mysql_db:
    name: "{{ app_db }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create App MySQL user and grants access to App DB
  mysql_user:
    name: "{{ app_user }}"
    password: "{{ app_pass }}"
    priv: "{{ app_db }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
