 - name: deploying property-finder-app to production server
   hosts: nodeslave
   become: true
   vars_files:
     - vault/main.yml
   roles:
     - setup
     - apache2
     - php
     - mysql
     - composer
     - node.js
     - deploy
