 - name: deploying property-finder-app to test server
   hosts: deploy
   become: true
   vars_files:
     - vars/main.yml
   roles:
     - git_env
       #- apache2
       #- php
       # - mysql
       #- composer
       # - node
       #- prod
