---
# tasks file for apache2

# Install apache2 via script
# - name: send apache2 installation script to prod server
#   template:
#     src: apache2.sh.j2
#     dest: "/home/ubuntu/apache2.sh"
#     mode: "0777"

# - name: exec apache2 script
#   command: sh /home/ubuntu/apache2.sh

- name: Install Apache2
  apt: name=apache2 update_cache=yes state=latest

# Apache2 Configuration
- name: copy vhost to prod server
  template:
    src: node.js.conf.j2
    dest: "{{vhost}}"

- name: Enables new site
  file:
    src: "/etc/apache2/sites-available/node.js.conf"
    dest: "/etc/apache2/sites-enabled/node.js.conf"
    state: link

- name: Removes default site
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent
