---
# tasks file for git_env

- name: update prod server
  command: apt update

- name: install git cli
  apt:
    name: git
    state: present

- name: clone app
  git:
    repo: "https://{{token}}@github.com/{{user}}/{{repo}}.git"
    dest: "{{codebase}}/{{repo}}"
    
- name: Make sure the remote app root exists and has the right permissions
  file:
    path: "{{ remote_www_root }}/{{ app_root_dir }}"
    state: directory
    mode: '0777'
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"

- name: Set up additional directory permissions for www-data user on bootstrap/cache folder
  file:
    path: "{{ remote_www_root }}/{{ app_root_dir }}/bootstrap/cache"
    state: directory
    mode: '0777'
    owner: "{{ remote_user }}"
    
- name: Set up additional directory permissions for www-data user on storage folder
  file:
    path: "{{ remote_www_root }}/{{ app_root_dir }}/storage/logs/laravel.log"
    mode: '0777'
    owner: "{{ remote_user }}"
    state: directory
  ignore_errors: yes

- name: enable rewrite
  shell: a2enmod rewrite
  become: yes
