---
# tasks file for prod

- name: send npm exec on prod server
  template:
    src: npm.sh.j2
    dest: "{{var}}/code/npm.sh"
    mode: "0777"

- name: exec script
  command: "sh {{var}}/code/npm.sh"

- name: send .env file
  template: 
    src: .env.j2
    dest: "{{var}}/code/.env"
