---
# tasks file for prod

# - name: send npm exec on prod server
#   template:
#     src: npm.sh.j2
#     dest: "{{var}}/code/npm.sh"
#     mode: "0777"

# - name: exec script
#   command: "sh {{var}}/code/npm.sh"

#==============================================================
# - name: Update packages based on package.json to their latest version.
#   npm:
#     path: "{{var}}/code"
#     state: latest
    
# - name: Install packages based on package.json.
#   npm:
#     path: "{{var}}/code"

# - name: send .env file
#   template: 
#     src: .env.j2
#     dest: "{{var}}/code/.env"

#============================================   
# - name: Run build-dev
#   shell: |
#   #  source $HOME/.nvm/nvm.sh
#     npm run watch
#   args:
#     executable: /bin/bash
#     chdir: "{{var}}/code"

- name: npm run watch
  command: "/usr/bin/npm run watch"
  args:
    chdir: "{{var}}/code"
    
# - name: npm run watch
#   command: "/usr/bin/npm {{var}}/code/run watch"
# #   tags: [ 'laravel', 'artisan:migrate' ]
  
  
