---
# tasks file for prod

- name: Update packages based on package.json to their latest version.
  npm:
    path: "{{var}}/code"
    state: latest
    
- name: Install packages based on package.json.
  npm:
    path: "{{var}}/code"

- name: send .env file
  template: 
    src: .env.j2
    dest: "{{var}}/code/.env"  

# - name: npm run watch
#   command: "sudo /usr/bin/npm run watch"
#   args:
#     chdir: "{{var}}/code"

- name: send exec mode to prod
  template: 
    src: laramode.sh.j2
    dest: "{{home}}/laramode.sh"
    mode: "0777"
    
- name: exec mode
  command: "sh {{home}}/laramode.sh"

- name: Installing Laravel dependencies
  command: composer install --no-interaction --working-dir="{{var}}/code"
  become: false

- name: Generate app key
  command: "/usr/bin/php {{var}}/code/artisan key:generate"
  tags: [ 'laravel', 'artisan:key' ]

- name: Set up app storage link
  command: "/usr/bin/php {{var}}/code/artisan storage:link"
  tags: [ 'laravel', 'artisan:storage' ]

- name: Run Migrations + Seeders
  command: "/usr/bin/php {{var}}/code/artisan migrate --seed --force"
  tags: [ 'laravel', 'artisan:migrate' ]
  
- name: Create dummy data for your database
  command: "/usr/bin/php {{var}}/code/artisan db:seed --class TestSeeder"
  tags: [ 'laravel', 'artisan:db:seed' ]
 

